---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi/democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  # valuesFrom:
  #   - kind: Secret
  #     name: democratic-csi-iscsi-values
  #     namespace: database
  #     valuesKey: values.yaml
  values:
    controller:
      externalAttacher:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      externalProvisioner:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      externalResizer:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      externalSnapshotter:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      driver:
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
    csiProxy:
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 150Mi
          ephemeral-storage: 200Mi
    csiDriver:
      name: org.democratic-csi.iscsi
    storageClasses:
      - name: nas-iscsi-store
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    volumeSnapshotClasses:
      - name: nas-iscsi-snap
        deletionPolicy: Delete
        parameters:
          detachedSnapshots: "true"
        secrets:
          snapshotter-secret:
    node:
      hostPID: true
      driver:
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
      driverRegistrar:
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      cleanup:
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id:
        httpConnection:
          protocol: http
          apiVersion: 2
          host: 192.168.8.129
          port: 80
          allowInsecure: true

          apiKey: ${SECRET_NAS_API_KEY}

        zfs:
          datasetParentName: hdd/k8s/iscsi/v
          detachedSnapshotsDatasetParentName: hdd/k8s/iscsi/s
          zvolCompression:
          zvolDedup:
          zvolEnableReservation: false
          zvolBlocksize:
        iscsi:
          targetPortal: "192.168.8.129:3260"
          interface:
          namePrefix: csi-
          nameSuffix: "-k8s-cluster"
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 8
              targetGroupAuthType: None
              targetGroupAuthGroup:
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: "SSD"
          extentAvailThreshold: 0
